/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.SwingUtilities;

/**
 *
 * @author huuph
 */
public class LoadTimeChao extends javax.swing.JFrame {

    /**
     * Creates new form LoadTimeChao1
     */
    public LoadTimeChao() {
        setUndecorated(true);
        initComponents();
        runLoadingBar();
        setLocationRelativeTo(this);

    }

    private void runLoadingBar() {
        class Loading extends Thread {

            @Override
            public void run() {
                for (int i = 0; i <= 100; i++) {
                    try {
                        Thread.sleep(30);
                        lblLoadingValue1.setText(i + "%");
                        ProgressBar1.setValue(i);
                        if (i == 100) {
                            dispose();
                            new Login().setVisible(true);
                        }
                    } catch (InterruptedException ex) {
                        Logger.getLogger(LoadTimeChao.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }

        }
        Loading l = new Loading();
        l.start();
    }

//    
//    private void runLoadingBar() {
//    class Loading extends Thread {
//        @Override
//        public void run() {
//            for (int i = 0; i <= 100; i++) {
//                final int progress = i;
//                try {
//                    Thread.sleep(20);
//                    SwingUtilities.invokeLater(new Runnable() {
//                        public void run() {
//                            lblLoadingValue1.setText(progress + "%");
//                            ProgressBar1.setValue(progress);
//                            if (progress < 50) {
//                                ProgressBar1.setForeground(new Color(0, 255, 34)); // Màu cam nhạt
//                            } else if (progress < 75) {
//                                ProgressBar1.setForeground(new Color(255, 175, 75)); // Màu cam đậm hơn
//                            } else {
//                                ProgressBar1.setForeground(new Color(255, 135, 0)); // Màu cam sẫm
//                            }
//                        }
//                    });
//                    if (progress == 100) {
//                        dispose();
//                        new Login().setVisible(true);
//                    }
//                } catch (InterruptedException ex) {
//                    Logger.getLogger(LoadTimeChao.class.getName()).log(Level.SEVERE, null, ex);
//                }
//            }
//        }
//    }
//    Loading l = new Loading();
//    l.start();
//}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblLoadingValue = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ProgressBar1 = new javax.swing.JProgressBar();
        lblLoading1 = new javax.swing.JLabel();
        lblLoadingValue1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        lblLoadingValue.setFont(new java.awt.Font("Segoe UI", 2, 13)); // NOI18N
        lblLoadingValue.setForeground(new java.awt.Color(255, 153, 51));
        lblLoadingValue.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoadingValue.setText("       0%");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hello");
        setBackground(new java.awt.Color(255, 255, 255));
        setName("Hello"); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        ProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        ProgressBar1.setForeground(new java.awt.Color(255, 255, 255));
        ProgressBar1.setBorder(null);
        ProgressBar1.setBorderPainted(false);
        ProgressBar1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                ProgressBar1AncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        lblLoading1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLoading1.setText(" Loading...");

        lblLoadingValue1.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblLoadingValue1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLoadingValue1.setText("0%");

        jLabel4.setBackground(new java.awt.Color(102, 102, 102));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 65)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 204, 102));
        jLabel4.setText("VAN NANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblLoading1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLoadingValue1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(ProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(132, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(127, 127, 127))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(101, 101, 101)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLoading1)
                    .addComponent(lblLoadingValue1))
                .addGap(0, 0, 0)
                .addComponent(ProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void ProgressBar1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_ProgressBar1AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_ProgressBar1AncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoadTimeChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoadTimeChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoadTimeChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadTimeChao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoadTimeChao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblLoading1;
    private javax.swing.JLabel lblLoadingValue;
    private javax.swing.JLabel lblLoadingValue1;
    // End of variables declaration//GEN-END:variables
}
